export const textColor = {
  primary: "text-primary",
  second: "text-second",
  third: "text-third",
  normal: "text-normal",
  fire: "text-fire",
  water: "text-water",
  electric: "text-electric",
  grass: "text-grass",
  ice: "text-ice",
  fighting: "text-fighting",
  poison: "text-poison",
  ground: "text-ground",
  flying: "text-flying",
  psychic: "text-psychic",
  bug: "text-bug",
  rock: "text-rock",
  ghost: "text-ghost",
  dragon: "text-dragon",
  dark: "text-dark",
  steel: "text-steel",
  fairy: "text-fairy",
  none: "text-none",
};

export const bgColor = {
  primary: "bg-primary",
  second: "bg-second",
  third: "bg-third",
  normal: "bg-normal",
  fire: "bg-fire",
  water: "bg-water",
  electric: "bg-electric",
  grass: "bg-grass",
  ice: "bg-ice",
  fighting: "bg-fighting",
  poison: "bg-poison",
  ground: "bg-ground",
  flying: "bg-flying",
  psychic: "bg-psychic",
  bug: "bg-bug",
  rock: "bg-rock",
  ghost: "bg-ghost",
  dragon: "bg-dragon",
  dark: "bg-dark",
  steel: "bg-steel",
  fairy: "bg-fairy",
  none: "bg-none",
};
